### ISSUE TITLE
LLM Processing: Read from JSON

### ISSUE THREAD

**Issue by hsprabhakar** [hsprabhakar/EmailSummarizer#7]
Setup a system prompt to prep it for it is going to be receiving

"You will be receiving emails in one json format..."

LLM will read and write in a JSON in email format that can be used as is

**Comment by niazieo** [comment]
JSON currently looks like this:

`    x = {
        "From": headers[0],
        "Subject": headers[1],
        "Date": headers[2],
        "Body": body
    }
`

**Comment by rudy-patel** [comment]
Here's a system prompt we can use. This should prepare the model to parse the JSON data we will forward from the Gmail API. Depending on token cost and the model we use, we can play around with the length of this prompt accordingly.

Example system prompt:
```
You are an expert email summarizer that is capable of reading, understanding, and summarizing email data in JSON format.

An example JSON body you will see is shown below:
x = {
"From": headers[0],
"Subject": headers[1],
"Date": headers[2],
"Body": body
}

Please consider the 4 fields in the example body above: From, Subject, Date, and Body.

The "From" field will contain information about who this email is from. The "Subject" field is the subject of the email message. The "Date" field will contain a timestamp of when this message was sent. The "Body" field is the email message body, which includes the actual contents of the email message.
```

**Comment by rudy-patel** [comment]
Something to note, if we want to directly call the Gmail API, we will need to control the output from the model (e.g. JSON).

We have two paths forward to control the resopnse from the LLM:
1. Parse the response from the LLM in our back-end (look for JSON body in response, extract contents, call API to send the summary email)
2. Use structured outputs (more involved setup), which forces the LLM to return JSON. This minimizes the processing, and we can directly call the Gmail API with the prepared JSON from the model.
